### ISSUE TITLE
[BUG] virt-install command  in create_vm.sh is killed by libvirtd

### ISSUE THREAD

**Issue by morvencao** [openshift/microshift#1161]
#### What happened?

Bootstrapping a virtual machine using the microshift-installer ISO image is often killed by libvirtd

```bash
VMNAME=microshift-edge
NETNAME=default

./scripts/image-builder/create-vm.sh $VMNAME $NETNAME
```

Then I found the virt-install command in create_vm.sh is killed by libvirtd:

```bash
$ tail /var/log/libvirt/qemu/microshift-edge.log
...
char device redirected to /dev/pts/1 (label charserial0)
2022-12-02T11:10:23.549098Z qemu-kvm: terminating on signal 15 from pid 9584 (<unknown process>)
2022-12-02 11:10:23.782+0000: shutting down, reason=shutdown

$ ps -ef | grep 9584
root        9584       1  0 11:07 ?        00:00:00 /usr/sbin/libvirtd --timeout 120
microsh+    9895    7439  0 11:11 pts/0    00:00:00 grep --color=auto 9584
```

As you  can see, `virt-install` command  in `create_vm.sh` was killed by libvirtd because of timeout(120s).

If I add `--wait 10` to let `virt-install` wait for 10 minutes, everything will be fine.

#### What did you expect to happen?

`virt-install` command  in create_vm.sh should not be killed by libvirtd

#### How to reproduce it (as minimally and precisely as possible)?
1. '...'
2. '...'

#### Environment
- MicroShift version (use `microshift version`):
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by ggiguash** [comment]
@morvencao, thank you for reporting this problem. 

The `scripts/image-builder/create-vm.sh` script is using `--noautoconsole` argument to `virt-install` to allow remote installation without display. Because of that, the VM is shutoff when even so the reboot is requested.
See `2022-12-02 11:10:23.782+0000: shutting down, reason=shutdown` from your log.

I will add `--wait`to the command to mitigate this behavior and have the VM rebooted to complete the installation.
