### ISSUE TITLE
[BUG] Cannot have fsGroup injected

### ISSUE THREAD

**Issue by clyang82** [openshift/microshift#754]
#### What happened:

I am trying to deploy the postgres into microshift. the postgres cannot be started successfully. the error is `Permission denied` to access `/etc/ssh/sshd_config`. the folder is mounted from a configmap. there is no `fsGroup` injected into the statefulset.

it works in KinD cluster or OCP cluster. for OCP cluster, scc can help to inject `fsGroup: xxx` so that the folder is accessible by that group. for KinD cluster, the `fsGroup: 26` is injected as well ( I do not how to do it) 

#### What you expected to happen:

the `fsGroup: 26` is injected so that the pod can be running normally.

#### How to reproduce it (as minimally and precisely as possible):

1.  `docker run -d --rm --name hub --privileged -v hub-data:/var/lib -p 36443:6443 quay.io/microshift/microshift-aio:latest` to start microshift
2. follow this document to deploy postgres https://access.crunchydata.com/documentation/postgres-operator/v5/quickstart/ into microshift

#### Anything else we need to know?:

Is it a bug or is it a designed behaviour? if it is a bug and was fixed, where can I get the latest image? Thanks.

#### Environment:
- Microshift version (use `microshift version`):  quay.io/microshift/microshift-aio:latest
- Hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by dhellmann** [comment]
The team is moving away from supporting deployment using podman and focusing on RPMs and systemd. The main branch has changed considerably since the 4.8 release, and as we're working on product builds we haven't been keeping the community build up to date. We do intend to resume work on Fedora support, but it may be a few months. In the mean time, if building from source from the main branch and deploying using systemd does not resolve this problem, please open a new issue with the details.
